### ISSUE TITLE
WLS2 Error on missing submodules.kicad_parser

### ISSUE THREAD

**Issue by ApoEXE** [leoheck/kiri#107]
The following error came up when trying to run the bin.

```
Traceback (most recent call last):
  File "/home/jav/kiri/bin/kicad6_sheet_instances.py", line 18, in <module>
    from submodules.kicad_parser.kicad_pcb import *
ModuleNotFoundError: No module named 'submodules.kicad_parser.kicad_pcb'
Traceback (most recent call last):
  File "/home/jav/kiri/bin/kicad6_sheet_instances.py", line 18, in <module>
    from submodules.kicad_parser.kicad_pcb import *
ModuleNotFoundError: No module named 'submodules.kicad_parser.kicad_pcb'
```

along with this ones:

```
/home/jav/kiri/bin/kiri: line 311: printf: copper_finish: invalid number
/home/jav/kiri/bin/kiri: line 311: printf: creategerberjobfile: invalid number
/home/jav/kiri/bin/kiri: line 311: printf: dashed_line_dash_ratio: invalid number
/home/jav/kiri/bin/kiri: line 311: printf: dashed_line_gap_ratio: invalid number
```

**Comment by leoheck** [comment]
Hi. Did you run the install_dependencies script?
